[package]
authors = ["Erb3", "Snowflake-Software"]
description = "Sync and backup service for the Iceblink 2FA manager"
edition = "2021"
name = "iceblink-sync"
version = "0.1.0"

[dependencies]
axum = {version = "0.7.7", features = ["macros"]}
axum-extra = {version = "0.9.4", features = ["cookie"]}
bon = "3.0.0"
chrono = "0.4.38"
clap = {version = "4.5.21", features = ["derive", "env"]}
dotenvy = {version = "0.15.7"}
jsonwebtoken = "9.3.0"
memory-serve = "0.6.0"
rand = "0.8.5"
regex = "1.11.1"
reqwest = {version = "0.12.9", features = ["json"]}
serde = {version = "1.0.215", features = ["derive"]}
serde_json = "1.0.132"
sqlx = {version = "0.8", features = ["chrono", "derive", "macros", "migrate", "runtime-tokio", "sqlite"]}
tokio = {version = "1.41.1", features = ["full"]}
tower = "0.5.1"
tower-http = {version = "0.6.1", features = ["compression-full", "cors", "timeout", "trace"]}
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
utoipa = {version = "5.2.0", features = ["axum_extras"]}
utoipa-axum = "0.1.2"
utoipa-swagger-ui = {version = "8.0.3", features = ["axum", "vendored"]}
