[package]
name = "iceblink-sync"
version = "0.1.0"
edition = "2021"
description = "Sync and backup service for the Iceblink 2FA manager"
authors = ["Snowflake-Software", "Erb3"]

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
axum = { version = "0.7.7", features = ["macros"] }
serde = { version = "1.0.215", features = ["derive"] }
clap = { version = "4.5.21", features = ["derive", "env"] }
memory-serve = "0.6.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tower-http = { version = "0.6.1", features = [
  "cors",
  "timeout",
  "compression-full",
  "trace",
] }
tower = "0.5.1"
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "sqlite",
  "macros",
  "derive",
  "migrate",
  "chrono",
] }
chrono = "0.4.38"
dotenvy = { version = "0.15.7" }
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["json"] }
jsonwebtoken = "9.3.0"
axum-extra = { version = "0.9.4", features = ["cookie"] }
regex = "1.11.1"
bon = "3.0.0"
