name: Sync Server CI

on:
  push:
    paths:
      - sync/**
      - .github/workflows/sync-ci.yml

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite:iceblink.db

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sync
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --component rustfmt --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./sync -> target
      - run: cargo install sqlx-cli --no-default-features --features sqlite
      - run: sqlx database setup
      - run: cargo build --verbose
      - run: cargo test --verbose
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./sync/Cargo.toml
          commit-message: "chore(sync): fmt"
